import Head from 'next/head';
import { Layout } from '@/components/Layout';
import { Heading } from '@/components/Heading';
import { PostTimeline } from '@/components/PostTimeline';
import { allPosts, Post } from 'contentlayer/generated';
import { compareDesc } from 'date-fns';
import type { InferGetStaticPropsType, GetStaticProps } from 'next';

export const getStaticProps: GetStaticProps<{ posts: Post[] }> = async () => {
  const posts = allPosts.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date));
  });

  return {
    props: {
      posts
    }
  };
};

export default function Blog({
  posts
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Eduardo Ambriz - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="mt-10 mb-32 flex max-w-5xl flex-col justify-center px-5 sm:mx-auto sm:items-center sm:text-center">
          <Heading
            level={1}
            className="mt-6 max-w-5xl text-5xl leading-snug sm:leading-tight"
          >
            Blog
          </Heading>
          <p className="mt-2 max-w-3xl text-lg leading-8 dark:text-slate-400 sm:mt-6">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat
            commodi illo sit deserunt ut?
          </p>
          <PostTimeline posts={posts} />
        </section>
      </Layout>
    </>
  );
}
