import Head from 'next/head';
import { Layout } from '@/components/Layout';
import { Heading } from '@/components/Heading';
import { PostTimeline } from '@/components/PostTimeline';

let posts = [
  {
    key: 'p01'
  },
  {
    key: 'p02'
  },
  {
    key: 'p03'
  }
];

export default function Blog() {
  return (
    <>
      <Head>
        <title>Eduardo Ambriz - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="mt-10 flex max-w-7xl flex-col justify-center px-5 sm:mx-auto sm:items-center sm:text-center">
          <Heading
            level={1}
            className="mt-6 max-w-5xl text-5xl leading-snug sm:leading-tight"
          >
            Blog
          </Heading>
          <p className="mt-2 max-w-3xl text-lg leading-8 dark:text-slate-400 sm:mt-6">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat
            commodi illo sit deserunt ut?
          </p>
          <PostTimeline posts={posts} />
        </section>
      </Layout>
    </>
  );
}
