import Head from 'next/head';
import Image from 'next/image';
import { Layout } from '@/components/Layout';
import { Heading } from '@/components/Heading';
import { Avatar } from '@/components/Avatar';
import { AnchorLink } from '@/components/AnchorLink';

let posts = [0, 1, 3];

export default function Home() {
  return (
    <>
      <Head>
        <title>Eduardo Ambriz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="mx-auto mt-20 flex max-w-7xl flex-col items-center justify-center px-7 text-center">
          <Avatar />
          <Heading
            level={1}
            className="mt-6 max-w-5xl text-5xl leading-snug md:text-6xl md:leading-tight"
          >
            FrontEnd Developer, JavaScript Enthusiast
          </Heading>
          <p className="mt-5 max-w-2xl text-xl leading-9">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
            aut laborum doloribus quos adipisci.
          </p>
        </section>
        <section className="mx-auto mt-20 flex max-w-7xl flex-col items-center justify-center px-7 text-center">
          <Heading
            level={2}
            className="mt-4 max-w-5xl text-4xl leading-snug tracking-wide md:text-5xl md:leading-tight"
          >
            Take a look at my work
          </Heading>
          <div className="mx-auto mt-10 grid w-full max-w-5xl grid-cols-1 items-center gap-y-14">
            <div>
              <div className="relative aspect-video w-full overflow-hidden rounded-lg border border-slate-200  dark:border-slate-700">
                <Image
                  src="/assets/projects/car-rental-react.png"
                  className="object-cover"
                  alt="project 1"
                  fill
                ></Image>
              </div>
              <div className="text-left">
                <Heading level={3} className="mt-6 text-lg">
                  car-rental-react
                </Heading>
                <p className="mt-2">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum,
                  consequuntur?
                </p>
                <AnchorLink
                  href="https://edroamz.github.io/car-rental-react/"
                  intent="primary"
                  className="mt-4 inline-block font-medium"
                >
                  https://edroamz.github.io/car-rental-react/
                </AnchorLink>
              </div>
            </div>
          </div>
        </section>
        <section className="mx-auto mt-20 flex max-w-5xl flex-col items-center justify-center px-7 text-center">
          <Heading
            level={2}
            className="mt-4 max-w-5xl text-4xl leading-snug tracking-wide md:text-5xl md:leading-tight"
          >
            Blog
          </Heading>
          <div className="relative mt-10 sm:ml-[calc(2rem+1px)] sm:pb-12 md:ml-[calc(3.5rem+1px)] lg:ml-[max(calc(14.5rem+1px),calc(100%-48rem))]">
            <div className="absolute top-3 bottom-0 right-full mr-7 hidden w-px bg-slate-200 dark:bg-slate-800 sm:block md:mr-[3.25rem]"></div>
            <div className="space-y-16">
              {posts.map((post) => (
                <article key={post} className="group relative text-left">
                  <div className="absolute -inset-y-2.5 -inset-x-4 group-hover:bg-slate-50/70 dark:group-hover:bg-slate-800/50 sm:rounded-2xl md:-inset-y-4 md:-inset-x-6"></div>
                  <svg
                    viewBox="0 0 9 9"
                    className="absolute right-full top-2 mr-6 hidden h-[calc(0.5rem+1px)] w-[calc(0.5rem+1px)] overflow-visible text-slate-200 dark:text-slate-600 sm:block md:mr-12"
                  >
                    <circle
                      cx="4.5"
                      cy="4.5"
                      r="4.5"
                      stroke="currentColor"
                      className="fill-white dark:fill-slate-900"
                      strokeWidth="2"
                    ></circle>
                  </svg>
                  <div className="relative">
                    <h3 className="pt-8 text-lg tracking-wider text-slate-900 dark:text-slate-200 lg:pt-0">
                      Protocol: A beautiful starting point for your next API
                      documentation site
                    </h3>
                    <div className="mt-2 mb-4 line-clamp-2">
                      <p className="leading-7">
                        It’s been months in the making but I’m excited to
                        finally release our next website template —{' '}
                        <a href="https://tailwindui.com/templates/protocol">
                          Protocol
                        </a>
                        , a beautiful starter kit for building amazing API
                        reference websites.
                      </p>
                    </div>
                    <dl className="absolute left-0 top-0 lg:left-auto lg:right-full lg:mr-[calc(6.5rem+1px)]">
                      <dt className="sr-only">Date</dt>
                      <dd className="whitespace-nowrap text-sm leading-6 dark:text-slate-400">
                        <time dateTime="2022-12-15T15:00:00.000Z">
                          December 15, 2022
                        </time>
                      </dd>
                    </dl>
                  </div>
                  <a
                    className="flex items-center text-sm font-medium tracking-wide text-blue-500 dark:text-blue-400"
                    href="/blog/2022-12-15-protocol-api-documentation-template"
                  >
                    <span className="absolute -inset-y-2.5 -inset-x-4 sm:rounded-2xl md:-inset-y-4 md:-inset-x-6"></span>
                    <span className="relative">
                      Read more
                      <span className="sr-only">
                        , Protocol: A beautiful starting point for your next API
                        documentation site
                      </span>
                    </span>
                    <svg
                      className="relative mt-px ml-2.5 overflow-visible text-sky-300 dark:text-sky-700"
                      width="3"
                      height="6"
                      viewBox="0 0 3 6"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M0 0L3 3L0 6"></path>
                    </svg>
                  </a>
                </article>
              ))}
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
}
