import Head from 'next/head';
import { Layout } from '@/components/Layout';
import { Heading } from '@/components/Heading';
import type { InferGetStaticPropsType, GetStaticProps } from 'next';
import { allPages, Page } from 'contentlayer/generated';
import { Mdx } from '@/components/Mdx';

export const getStaticProps: GetStaticProps<{ page?: Page }> = async () => {
  let page = allPages.find((page) => page.title === 'Uses');

  return {
    props: {
      page
    }
  };
};

export default function Uses({
  page
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Eduardo Ambriz - Uses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="mx-auto mt-10 mb-32 flex max-w-3xl flex-col items-center px-6">
          <div className="mb-12 w-full text-left sm:text-center">
            <Heading
              level={1}
              className="mt-6 max-w-5xl text-5xl leading-snug sm:leading-tight"
            >
              Uses
            </Heading>
            <p className="mt-2 max-w-3xl text-lg leading-8 dark:text-slate-400 sm:mt-6">
              {page?.description}
            </p>
          </div>
          {page && (
            <div className="w-full">
              <Mdx code={page.body.code} />
            </div>
          )}
        </section>
      </Layout>
    </>
  );
}
