import Head from 'next/head';
import { Layout } from '@/components/Layout';
import { Heading } from '@/components/Heading';

export default function Uses() {
  return (
    <>
      <Head>
        <title>Eduardo Ambriz - Uses</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section className="mt-10 mb-32 flex max-w-7xl flex-col justify-center px-5 sm:mx-auto sm:items-center sm:text-center">
          <Heading
            level={1}
            className="mt-6 max-w-5xl text-5xl leading-snug sm:leading-tight"
          >
            Uses
          </Heading>
          <p className="mt-2 max-w-3xl text-lg leading-8 dark:text-slate-400 sm:mt-6">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae
            adipisci voluptas doloremque deleniti rem?
          </p>
        </section>
      </Layout>
    </>
  );
}
